osx_image: xcode8
language: objective-c
script:
  - set -o pipefail && xcodebuild build -project NibDesignableDemo/NibDesignableDemo.xcodeproj -scheme NibDesignableDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0'| xcpretty -f `xcpretty-travis-formatter`
  - set -o pipefail && xcodebuild test -project NibDesignableDemo/NibDesignableDemo.xcodeproj -scheme NibDesignableDemo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0'| xcpretty -f `xcpretty-travis-formatter`
  - swiftlint lint --strict
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - gem install xcpretty xcpretty-travis-formatter
